[package]
authors = ["yamakaky"]
name = "toyunda-player-rs"
version = "0.1.0"

[dependencies]
docopt = "0.6.78"
enum_primitive = "0.1.0"
gl = "0.5.2"
libc = "0.2.7"
num = "0.1.31"
rustc-serialize = "0.3.18"
sdl2 = "0.16.0"
